gems:
  - jekyll-sitemap
  - jekyll-paginate

timezone: Europe/London

title: Minecraft Pocket Edition

excerpt_separator: <!--read more-->

collections:
  wiki:
    output: true
    permalink: /wiki/:path/
  mobileconfig:
    output: true
    permalink: /wiki/software/pocketmine/realms.mobileconfig

defaults:
  - scope:
      path: ""
      type: pages
  - scope:
      path: ""
      type: wiki
  - scope:
      path: "/wiki/software/server/pocketmine/realms.mobileconfig"
      type: mobileconfig
    values:
      layout: wiki
      secondarytitle: MCPE Wiki
